### ISSUE TITLE
Jasmine helpers being unloaded but not reloaded

### ISSUE THREAD

**Issue by mrozbarry** [sindresorhus/gulp-jasmine#61]
I am using the main jasmine npm module (not jasmine-node or variants of that), and running my tests inside a gulp watch task.

The first run of my test works perfectly, but on the second run, my helpers are unloaded and no longer available.  What's going on here?  I see some other [similar/related](https://github.com/sindresorhus/gulp-jasmine/pull/36) pull requests and read through a few similar issues.

I tried using gulp-shell to execute my tests, but that fails because of an environment setup problem (using wemux on a remote server with other people which seems to kill permissions in child processes).

What's my best option for automatically re-loading my helpers without modifying all my tests?  I have many files, and it wouldn't be feasable (in terms of maintenance) to manually `require(...)` the helpers in each one.

**Comment by jbblanchet** [comment]
Closing because not an issue AND not related to gulp-jasmine. Stack overflow would be a much better option for asking such a question.

I can still say that if you look at the source code, there's a well identified section of code that clears the cache. Not sure if that's your problem, but it's as good a place as any to start.

**Comment by mrozbarry** [comment]
Yes, the cache is cleared, but gulp-jasmine does not reload my helpers.  This is certainly an issue with gulp-jasmine, unless I misunderstand the scope of this repo.

**Comment by jbblanchet** [comment]
I'm not sure I understand what you're doing. Are you using gulp-jasmine to run your tests, or are you using jasmine directly through the shell?

**Comment by mrozbarry** [comment]
I have tried both.  I would prefer using gulp-jasmine, but when I run it in a watch task, the first time it detects a change, jasmine runs as expected - the second time, it runs but fails on all tests that use any helper libraries I'm loading in (ie jasmine-matchers, and other similar tools).  These are installed as node_modules, which I'm under the impression is being cleared in the cache delete, so it means either jasmine doesn't know to re-require the helpers, or gulp-jasmine isn't reloading those.

**Comment by jbblanchet** [comment]
OK, sorry I misunderstood your problem. I'll reopen the issue. Do you have a simplified code sample of a test file so I can try to reproduce your issue?

**Comment by mrozbarry** [comment]
Sure

**gulpfile.js**
```
var coffee, gulp, gutil, jasmine, rm, watch;

gulp = require('gulp');
jasmine = require('gulp-jasmine');
watch = require('gulp-watch');
coffee = require('gulp-coffee');
gutil = require('gulp-util');
rm = require('gulp-rm');

gulp.task('test', ['jasmine']);

gulp.task('watch', function() {
  return watch(['app/**/*.coffee', 'spec/**/*.coffee'], function() {
    return gulp.run(['clean', 'compile', 'test']);
  });
});

gulp.task('clean', function() {
  return gulp.src(['./spec/full/**/*.js', './spec/factories/*.js', './spec/fixtures/*.js']).pipe(rm());
});

gulp.task('compile', ['clean'], function() {
  return gulp.src('./spec/**/*.coffee').pipe(coffee({
    bare: true
  })).on('error', gutil.log).pipe(gulp.dest('./spec/'));
});

gulp.task('jasmine', ['compile'], function() {
  return gulp.src('./spec/**/*.spec.js').pipe(jasmine({
    config: require('./spec/support/jasmine.json')
  }));
});
```

**spec/support/jasmine.json**
```
{
  "spec_dir": "spec",
  "spec_files": [
    "**/*.spec.js"
  ],
  "helpers": [
    "helpers/**/*.js"
  ]
}
```

Running `gulp test` works perfectly.  Running `gulp watch` seems to run fine; I can trigger the test task when I save a file as expected, but when I trigger the task by saving a second time, I get a ton of errors saying the methods the helpers install are no longer available.

My tests are all written in coffeescript, and they are compiled into javascript, and the fact that `gulp test` works every time tells me this isn't the issue, so I just wanted to clear that off the table.

**Comment by jbblanchet** [comment]
Good news is I'm able to reproduce your problem. Bad news is, I'm not familiar with the helpers and their usage. I understand what's happening, but I don't understand the fix yet.

When we load the config, the helper files are identified correctly. When jasmine is executed, it calls the [loadHelpers](https://github.com/jasmine/jasmine-npm/blob/793b7bb4f3ba4f420c7183b825ec477ebcf6eb52/lib/jasmine.js#L75) method that requires each helper file. Since the node require mechanism is used, these files are cached. Every other require will simply use the cache, and the file will not be run again.

When the helper is required for the first time, you attach some methods to the jasmine instance. When your tests are run again, we use a new jasmine instance, and since the files have been cached, they are not executed again.

We normally clear the cache for every spec files and its children since they are loaded through gulp. We do not do that with helper files. The most obvious solution would be to clear the files in gulp-jasmine, but that would imply either reading the config file ourselves, or accessing the lists of helpers file and clearing them from the cache just before we run the execute method. My favorite method would be for jasmine to clear the cached files itself, but I'm not sure if they're interested in such a solution.

@sindresorhus @amavisca what do you think?

**Comment by jbblanchet** [comment]
Submitted a pull request, @mrozbarry if you could try it to confirm it fixes your issue it would be appreciated.
