### ISSUE TITLE
Jasmine doesn't seems to recognize my js functions

### ISSUE THREAD

**Issue by wellingtonamaralleitao** [sindresorhus/gulp-jasmine#72]
I'm trying to make a task to execute some tests on my scripts. Therefore when I call a function on spec files it says that my **functions are not defined**.

e.g: 

**spec.js**
``` javascript
describe("A suite", function() {
  it("contains spec with an expectation", function() {
  	var a = returnNumber();
    expect(a).toBe(1);
  });
});
```

Thats the task I've been working on:  
``` javascript
var jasmine = require('gulp-jasmine');

gulp.task('default', () =>
    gulp.src('assets/js/*.js')
        .pipe(jasmine({
            config: {
			    spec_dir: 'assets',
			    spec_files: [
			        'js/spec/*.js'
			    ],
			    helpers: [
			        'js/src/*.js'
			    ]
			}
        }))
);
```

**Comment by jbblanchet** [comment]
Hi!

When you say that your functions are not defined, you mean returnNumber()? Is that a helper, or the method you want to test?

**Comment by wellingtonamaralleitao** [comment]
The returnNumber func is at `js/src/*.js`. Shouldn't the helpers property define my functions so I could be able to call on my spec. Sorry if it is a stupid question I'm still new using jasmine.

**Comment by jbblanchet** [comment]
I never use helpers, so I might not be the best reference, but your problem seems similar to https://github.com/jasmine/jasmine-npm/issues/25.

If you want to test the files in js/src with the specs in js/spec, here's how to use gulp-jasmine:

```
gulp.task('default, () =>
  gulp.src('js/spec/*.spec.js') // your source is your specs
    .pipe(jasmine())
);
```

Then you would import your source files in the spec:
```
var moduleToTest = require('../src/moduleToTest');

describe('a test suite', () => {
  it('works', () => {
    var a = moduleToTest.returnNumber();
    expect(a).toBe(1);
  });
});
```

This doesn't appear to be an issue with gulp-jasmine, so I'll close this. Feel free to comment if you think otherwise.
